#!/usr/local/bin/python3.12
# -*- coding: utf-8 -*-
import os
import sys
import subprocess
import random

def validate_args(config, model, seed=None):
    assert os.path.isfile(config)
    assert os.path.isfile(model)
    if not seed is None:
        int(seed)

def build_log_path(log_name):
    if os.path.dirname(log_name) != "logs":
        return os.path.join("logs", log_name)

def build_run_config(raw_args):
    if len(raw_args) == 3:
        config, model, log_name = raw_args
        seed = str(random.randint(1000, 0xffff))
    else:
        config, model, log_name, seed = raw_args

    validate_args(config, model, seed)
    log_path = build_log_path(log_name)

    return dict(
            config=config,
            model=model,
            log_path=log_path,
            seed=seed
        )

if __name__ == "__main__":
    run_file = sys.argv[1]

    with open(run_file, "r") as f:
        run_args = f.readlines()

    runs = []
    print("=" * 30)

    for run_arg in run_args:
        print(f"Processing line: {run_arg}")

        args = run_arg.strip().split()
        if len(args) < 3 or len(args) > 4:
            raise Exception("Number of args must be 3 or 4: config file - checkpoint model - log file name - seed")
        else:
            run_conf = build_run_config(args)
            runs.append(run_conf)

            print(f"Parsed config: {run_conf}")
            print("-" * 30)

    for run in runs:
        argvs = [
                "torchrun",
                "--master_port=7777",
                "/app/train.py",
                "--use-amp",
                "-c",
                run["config"],
                "--seed",
                run["seed"],
                "-t",
                run["model"],
            ]

        with subprocess.Popen(argvs, bufsize=1, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, universal_newlines=True) as p:
            if not p.stdout is None:
                log_file_path = run["log_path"]
                with open(log_file_path, "w") as f:
                    for line in p.stdout:
                        f.write(line)
                        print(line)

            if p.returncode != 0:
                raise ChildProcessError(p.returncode, p.args)

